name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Vérifiez le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure la version de Swift
      - name: Set up Swift
        uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "6.0.3"

      # Affiche la version de Swift utilisée
      - name: Show Swift version
        run: swift --version

      # Construisez le package
      - name: Build package
        run: swift build

      # Exécutez les tests
      - name: Run tests
        run: swift test
