name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Vérifiez le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Xcode (optionnel, mais recommandé pour clarifier)
      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      # Installer les dépendances si vous utilisez SPM
      - name: Resolve Dependencies
        run: xcodebuild -resolvePackageDependencies

      # Nettoyer le projet
      - name: Clean build
        run: xcodebuild clean -scheme Showdown-Master-Referee

      # Construire et tester
      - name: Build and test
        run: |
          xcodebuild test \
            -scheme Showdown-Master-Referee \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
