name: CI-iOS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest  # Utilisation de macOS standard, vous pouvez spécifier 'macos-12' ou une autre version si besoin

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app  # Assurez-vous que cette version est installée dans le runner

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -workspace HECKERNICOLAS_12_07082024/Showdown-Master-Referee.xcworkspace \
          -scheme "CI_iOS" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2" \
          ONLY_ACTIVE_ARCH=YES
